version: '3.8'
services:
  stat-server:
    build: ./stat-service/stat-server
    image: ewm-stats-server-image
    container_name: ewm-stats
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/ewm-stats
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres

  stats-db:
    image: postgres:14-alpine
    container_name: stats-db-container
    ports:
      - "6543:5432"

    environment:
      - POSTGRES_DB=ewm-stats
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=denis1


  main-service:
    build: ./main-service
    image: main-service-image
    container_name: main_service-container
    ports:
      - "8080:8080"
    depends_on:
      - main-db
      - stat-server
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://main-db:5432/main-service
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=Denis1

  main-db:
    image: postgres:14-alpine
    container_name: main-db-container
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=main-service
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=denis1
