version: '3.8'
services:
  stat-service:
    build: ./stat-service/stat-server
    container_name: stat
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/stat
      - DATABASE_NAME=postgres
      - DATABASE_PASSWORD=postgres

  stats-db:
    image: postgres:15-alpine
    container_name: stats-db
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=stat
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres


  main-service:
    build: ./main-service
    container_name: main-service
    ports:
      - "8080:8080"
    depends_on:
      - main-db
      - stat-service
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://main-db:5432/main
      - DATABASE_NAME=postgres
      - DATABASE_PASSWORD=postgres

  main-db:
    image: postgres:15-alpine
    container_name: main-db
    ports:
      - "6542:5432"
    environment:
      - POSTGRES_DB=main
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres